; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = wicked_pickandplace_ota

[env:wicked_pickandplace]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.flash_size = 4MB
lib_deps =
    gin66/FastAccelStepper
    ESP32Async/AsyncTCP @ 3.3.2
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ayushsharma82/ElegantOTA
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
monitor_filters = esp32_exception_decoder
upload_speed = 115200

[env:wicked_pickandplace_ota]
extends = env:wicked_pickandplace
upload_protocol = espota
;upload_port = wickedpickandplace.local
; ha az mDNS nem oldódik fel megbizhatoan a haloizatodon, hasznald helyette
; az eszkoz IP-cimet közvetlenul, pl.:
upload_port = 192.168.1.66
